name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: btj93/github-pages-blog-action@v0.0.17
        with:
          branch: gh-pages # Optional branch for GitHub Pages
